easy_admin:
  entities:
    Product:
      list:
        fields:
          - { property: 'image_name', type: 'image', base_path: '%app.path.product_images%' }
      form:
        fields:
          - { property: 'imageFile', type: 'file' }
      show:
        fields:
          - { property: 'image_name', type: 'image', base_path: '%app.path.product_images%' }
